# fly.toml app configuration file generated for ofahofah on 2024-01-10T05:54:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ofahofah"
primary_region = "cdg"

[build]
  image = "lamyas92/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dsqdwt0ti"
  CloudinarySettings__ApiKey="446336774161842"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
